import React, { useEffect, useRef, useState } from 'react'
import { Archive, ArrowLeft, Bot, CheckCircle2, ChevronRight, CircleAlert, Clock3, FilePlus2, FileText, FolderOpen, Link2, LoaderCircle, Map, MoreHorizontal, Network, Plus, Search, Settings2, Sparkles, Upload, X } from 'lucide-react'
import type { AnalysisStatus, AnalysisSummary, Material, ModelSettings, ProviderProfile, Relation, Topic, TopicMap, Workspace, Workstream } from './types'

const materialIcon = (type: string) => type === 'link' ? <Link2 size={16}/> : type === 'note' ? <FilePlus2 size={16}/> : <FileText size={16}/>
const toDay = (value?: string | null) => value ? new Intl.DateTimeFormat('zh-CN', { month: 'short', day: 'numeric' }).format(new Date(value)) : '未标记日期'
const workstreamOf = (material: TopicMap['materials'][number]) => material.workstreamId ?? null

export default function App(): React.ReactElement {
  const [workspace, setWorkspace] = useState<Workspace | null>(null)
  const [recentWorkspaces, setRecentWorkspaces] = useState<Array<{ root: string; name: string; openedAt: string }>>([])
  const [showWorkspaceMenu, setShowWorkspaceMenu] = useState(false)
  const [materials, setMaterials] = useState<Material[]>([])
  const [topics, setTopics] = useState<Topic[]>([])
  const [selected, setSelected] = useState<Material | null>(null)
  const [activeTopic, setActiveTopic] = useState<TopicMap | null>(null)
  const [query, setQuery] = useState('')
  const [answer, setAnswer] = useState<{ answer: string; citations: Array<{ id: string; title: string }> } | null>(null)
  const [showNote, setShowNote] = useState(false)
  const [showLink, setShowLink] = useState(false)
  const [showTopic, setShowTopic] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [workspaceRoot, setWorkspaceRoot] = useState<string | null>(null)
  const [message, setMessage] = useState('')
  const [contextMenu, setContextMenu] = useState<{ material: Material; x: number; y: number } | null>(null)
  const refreshRecent = async () => setRecentWorkspaces(await window.materialMap.workspace.recent())
  const refresh = async () => { if (!workspace) return; const [nextMaterials, nextTopics] = await Promise.all([window.materialMap.materials.list(), window.materialMap.topics.list()]); setMaterials(nextMaterials as Material[]); setTopics(nextTopics as Topic[]) }
  useEffect(() => { void refresh() }, [workspace])
  useEffect(() => { void refreshRecent(); window.materialMap.workspace.onMenu('workspace:new', () => void createWorkspace()); window.materialMap.workspace.onMenu('workspace:open', () => void openWorkspace()); window.materialMap.workspace.onMenu('workspace:close', () => setWorkspace(null)) }, [])
  useEffect(() => { if (!selected) return; const next = materials.find((item) => item.id === selected.id); if (next) setSelected(next) }, [materials])
  const openTopic = async (topic: Topic) => { setActiveTopic(await window.materialMap.topics.map(topic.id) as TopicMap); setSelected(null) }
  const importFiles = async () => { const files = await window.materialMap.chooseFiles(); for (const file of files) { const result = await window.materialMap.materials.import(file, false) as { duplicateOf?: Material }; if (result.duplicateOf) setMessage(`“${result.duplicateOf.title}” 已在工作区中。`) } await refresh() }
  const createWorkspace = async () => { try { const root = await window.materialMap.chooseDirectory(); if (root) setWorkspaceRoot(root) } catch (error) { setMessage(error instanceof Error ? error.message : '无法选择文件夹') } }
  const openWorkspace = async () => { const root = await window.materialMap.chooseDirectory(); if (!root) return; try { setWorkspace(await window.materialMap.workspace.open(root) as Workspace); await refreshRecent() } catch (error) { setMessage(error instanceof Error ? error.message : '无法打开工作区') } }
  const openRecent = async (root: string) => { try { setWorkspace(await window.materialMap.workspace.open(root) as Workspace); await refreshRecent() } catch { setMessage('这个工作区已无法打开，请确认文件夹仍然存在。') } }
  const createDemo = async () => { try { const topic = await window.materialMap.demo.create() as Topic; await refresh(); await openTopic(topic); setMessage('已创建 AI 关联演示，正在分析主题材料。') } catch (error) { setMessage(error instanceof Error ? error.message : '无法创建 AI 演示。') } }
  if (!workspace) return <><Welcome recent={recentWorkspaces} onCreate={createWorkspace} onOpen={openWorkspace} onRecent={openRecent} onForget={async (root) => { await window.materialMap.workspace.forgetRecent(root); await refreshRecent() }}/>{workspaceRoot && <WorkspaceDialog root={workspaceRoot} onClose={() => setWorkspaceRoot(null)} onSave={async (name) => { try { setWorkspace(await window.materialMap.workspace.create(workspaceRoot, name) as Workspace); setWorkspaceRoot(null); await refreshRecent() } catch (error) { setMessage(error instanceof Error ? error.message : '无法创建工作区') } }}/>} {message && <div className="toast"><CircleAlert size={17}/>{message}<button onClick={() => setMessage('')}><X size={15}/></button></div>}</>
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Network size={19}/></div><span>Material Map</span></div><button className="workspace-switch" onClick={() => setShowWorkspaceMenu(!showWorkspaceMenu)}><span className="workspace-dot"/><span>{workspace.name}</span><ChevronRight size={15}/></button>{showWorkspaceMenu && <div className="workspace-popover"><button onClick={() => void createWorkspace()}>新建工作区</button><button onClick={() => void openWorkspace()}>打开工作区</button>{recentWorkspaces.filter((item) => item.root !== workspace.root).slice(0, 6).map((item) => <button key={item.root} onClick={() => void openRecent(item.root)}>{item.name}</button>)}<button onClick={() => setWorkspace(null)}>关闭工作区</button></div>}<nav><button className={!activeTopic ? 'nav-item active' : 'nav-item'} onClick={() => { setActiveTopic(null); setSelected(null) }}><Archive size={17}/>工作台</button><div className="nav-section"><span>主题</span><button title="新建主题" onClick={() => setShowTopic(true)}><Plus size={15}/></button></div>{topics.map((topic) => <button key={topic.id} className={activeTopic?.topic.id === topic.id ? 'topic-item active' : 'topic-item'} onClick={() => void openTopic(topic)}><Map size={15}/>{topic.name}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={() => setShowSettings(true)}><Settings2 size={17}/>模型与隐私</button><button className="nav-item" onClick={async () => { const destination = await window.materialMap.savePackage(); if (destination) { await window.materialMap.workspace.export(destination); setMessage('工作区已导出。') } }}><Upload size={17}/>导出工作区</button></div></aside>
    <main className="main"><header className="topbar"><div>{activeTopic ? <><button className="back-button" onClick={() => setActiveTopic(null)}><ArrowLeft size={17}/>工作台</button><h1>{activeTopic.topic.name}</h1></> : <><h1>工作台</h1><p>最近导入的材料，正在逐渐连成脉络。</p></>}</div><div className="top-actions"><label className="search"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && query.trim()) void window.materialMap.ask(query).then(setAnswer) }} placeholder="搜索材料"/></label><button className="icon-button" title="基于本地材料提问" disabled={!query.trim()} onClick={() => void window.materialMap.ask(query).then(setAnswer)}><Bot size={18}/></button><button className="icon-button" title="导入文件" onClick={() => void importFiles()}><Upload size={18}/></button><button className="primary-button" onClick={() => setShowNote(true)}><Plus size={17}/>新建材料</button></div></header>
    {answer && <section className="answer-panel"><div className="answer-heading"><span><Bot size={16}/>基于本地材料的回答</span><button className="icon-button" onClick={() => setAnswer(null)}><X size={15}/></button></div><p>{answer.answer}</p>{answer.citations.length > 0 && <div className="citations">{answer.citations.map((citation) => <button key={citation.id} onClick={() => { const material = materials.find((item) => item.id === citation.id); if (material) setSelected(material) }}><FileText size={13}/>{citation.title}</button>)}</div>}</section>}{activeTopic ? <TopicCanvas map={activeTopic} materials={materials} onRefresh={async () => { const next = await window.materialMap.topics.map(activeTopic.topic.id) as TopicMap; setActiveTopic(next); await refresh() }} onSelect={setSelected} onContext={(material, x, y) => setContextMenu({ material, x, y })}/> : <Workbench materials={materials.filter((item) => !query || `${item.title} ${item.excerpt ?? ''}`.toLowerCase().includes(query.toLowerCase()))} onSelect={setSelected} onContext={(material, x, y) => setContextMenu({ material, x, y })} onImport={importFiles} onLink={() => setShowLink(true)} onDemo={() => void createDemo()} />}</main>
    {selected && <ContextPanel material={selected} topics={topics} activeTopic={activeTopic} onClose={() => setSelected(null)} onRefresh={refresh} onOpenTopic={openTopic} />}
    {showNote && <NoteDialog onClose={() => setShowNote(false)} onSave={async (title, text, format) => { if (format === 'note') await window.materialMap.materials.note(title, text); else await window.materialMap.materials.document(title, text, format); setShowNote(false); await refresh() }}/>} {showLink && <LinkDialog onClose={() => setShowLink(false)} onSave={async (url) => { await window.materialMap.materials.link(url); setShowLink(false); await refresh() }}/>} {showTopic && <TopicDialog onClose={() => setShowTopic(false)} onSave={async (name, description) => { const topic = await window.materialMap.topics.create(name, description) as Topic; setShowTopic(false); await refresh(); void openTopic(topic) }}/>} {showSettings && <SettingsDialog topicId={activeTopic?.topic.id} onClose={() => setShowSettings(false)} />}
    {contextMenu && <MaterialMenu material={contextMenu.material} x={contextMenu.x} y={contextMenu.y} onClose={() => setContextMenu(null)} onOpen={() => setSelected(contextMenu.material)} onRefresh={refresh} onMessage={setMessage}/>} 
    {message && <div className="toast"><CircleAlert size={17}/>{message}<button onClick={() => setMessage('')}><X size={15}/></button></div>}
  </div>
}

function Welcome({ recent, onCreate, onOpen, onRecent, onForget }: { recent: Array<{ root: string; name: string; openedAt: string }>; onCreate(): void; onOpen(): void; onRecent(root: string): void; onForget(root: string): void }): React.ReactElement { return <div className="welcome"><div className="welcome-mark"><Network size={32}/></div><p className="eyebrow">LOCAL MATERIAL MAP</p><h1>让材料自己长出脉络。</h1><p className="welcome-copy">文件、笔记和链接都保留在自己的工作区。导入后，按你的主题和时间慢慢形成一张可编辑的材料地图。</p><div className="welcome-actions"><button className="primary-button large" onClick={onCreate}><Plus size={18}/>创建工作区</button><button className="secondary-button large" onClick={onOpen}><FolderOpen size={18}/>打开工作区</button></div>{recent.length > 0 && <div className="recent-workspaces"><h2>最近工作区</h2>{recent.map((item) => <div key={item.root}><button onClick={() => onRecent(item.root)}><FolderOpen size={15}/><span>{item.name}</span><small>{item.root}</small></button><button title="从最近列表移除" onClick={() => onForget(item.root)}><X size={14}/></button></div>)}</div>}<div className="welcome-steps"><span>1. 建立本地工作区</span><span>2. 导入你的材料</span><span>3. 配置自己的 AI</span></div></div> }
function WorkspaceDialog({ root, onClose, onSave }: { root: string; onClose(): void; onSave(name: string): void }): React.ReactElement { const [name, setName] = useState('我的材料'); return <Modal title="创建工作区" onClose={onClose}><p className="dialog-note">将在此文件夹中保存材料副本、索引和地图数据。</p><input value={root} readOnly aria-label="工作区位置"/><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="工作区名称"/><button className="primary-button" disabled={!name.trim()} onClick={() => onSave(name.trim())}>创建工作区</button></Modal> }
function Workbench({ materials, onSelect, onContext, onImport, onLink, onDemo }: { materials: Material[]; onSelect(material: Material): void; onContext(material: Material, x: number, y: number): void; onImport(): void; onLink(): void; onDemo(): void }): React.ReactElement { return <section className="workbench">{materials.length === 0 ? <div className="empty-state"><div className="empty-icon"><Upload size={25}/></div><h2>从一份材料开始</h2><p>拖入文件、写一段笔记，或者留下一条链接。</p><div><button className="primary-button" onClick={onImport}><Upload size={17}/>导入文件</button><button className="secondary-button" onClick={onLink}><Link2 size={17}/>添加链接</button></div></div> : <><div className="section-heading"><div><h2>最近导入</h2><p>材料完成分析后会自动补充摘要与关联。</p></div><div className="workbench-actions"><button className="secondary-button" onClick={onDemo}><Sparkles size={15}/>创建 AI 演示</button><span>{materials.length} 份材料</span></div></div><div className="material-grid">{materials.map((material) => <MaterialCard key={material.id} material={material} onClick={() => onSelect(material)} onContext={(x, y) => onContext(material, x, y)}/>)}</div></>}</section> }
function MaterialCard({ material, onClick, onContext }: { material: Material; onClick(): void; onContext(x:number,y:number): void }): React.ReactElement { return <button className="material-card" onClick={onClick} onContextMenu={(event) => { event.preventDefault(); onContext(event.clientX, event.clientY) }}><div className={`material-type ${material.type}`}>{materialIcon(material.type)}<span>{material.type === 'file' ? '文件' : material.type === 'document' ? '文档' : material.type === 'note' ? '笔记' : '链接'}</span></div><h3>{material.title}</h3><p>{material.excerpt || material.error || (material.status === 'running' ? '正在解析材料…' : '等待分析材料内容')}</p><div className="card-footer"><span><Clock3 size={13}/>{toDay(material.occurredAt)}</span><Status status={material.status}/></div></button> }
function MaterialMenu({ material, x, y, onClose, onOpen, onRefresh, onMessage }: { material: Material; x:number; y:number; onClose(): void; onOpen(): void; onRefresh(): Promise<void>; onMessage(message:string): void }): React.ReactElement {
  const editable = material.type === 'note' || material.type === 'document' || (material.type === 'file' && /\.(md|txt|csv|json|html?)$/i.test(material.sourcePath ?? material.storedPath ?? ''))
  const act = async (action: () => Promise<unknown>, message: string) => { try { await action(); await onRefresh(); onMessage(message) } catch (error) { onMessage(error instanceof Error ? error.message : '操作失败。') } finally { onClose() } }
  return <div className="material-menu" style={{ left: x, top: y }} onMouseLeave={onClose}>
    <button onClick={() => { onOpen(); onClose() }}>{editable ? '编辑内容' : '查看材料'}</button>
    <button onClick={() => void act(() => window.materialMap.materials.open(material.id), '已交给默认程序打开。')}>{material.type === 'link' ? '打开链接' : '用默认程序打开'}</button>
    <button onClick={() => { const title = window.prompt('材料名称', material.title); if (title?.trim()) void act(() => window.materialMap.materials.rename(material.id, title), '材料已重命名。') }}>重命名</button>
    {material.sourcePath && <button onClick={() => void act(() => window.materialMap.materials.importNewVersion(material.id), '已导入为新版本。')}>导入为新版本</button>}
    <button className="danger" onClick={() => { if (window.confirm(`删除“${material.title}”？原始导入文件不会被删除。`)) void act(() => window.materialMap.materials.delete(material.id), '材料已删除。') }}>删除材料</button>
  </div>
}
function Status({ status }: { status: string }): React.ReactElement { if (status === 'complete') return <span className="status complete"><CheckCircle2 size={13}/>已整理</span>; if (status === 'failed') return <span className="status failed"><CircleAlert size={13}/>需重试</span>; return <span className="status pending"><LoaderCircle size={13}/>处理中</span> }
function MaterialPreview({ material, text }: { material: Material; text: string }): React.ReactElement {
  const extension = (material.sourcePath ?? material.storedPath ?? '').split('.').pop()?.toLowerCase()
  if (extension === 'html' || extension === 'htm') return <iframe className="document-preview-frame" sandbox="" title="HTML preview" srcDoc={text}/>
  if (extension === 'json') { try { return <pre>{JSON.stringify(JSON.parse(text || '{}'), null, 2)}</pre> } catch { return <pre className="preview-error">JSON 格式无效</pre> } }
  if (extension === 'csv') { const rows = text.split(/\r?\n/).filter(Boolean).slice(0, 30).map((row) => row.split(',')); return <table><tbody>{rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, index) => <td key={index}>{cell.trim()}</td>)}</tr>)}</tbody></table> }
  if (extension === 'md' || material.mimeType === 'text/markdown') return <div className="markdown-preview">{text.split(/\r?\n/).map((line, index) => line.startsWith('### ') ? <h3 key={index}>{line.slice(4)}</h3> : line.startsWith('## ') ? <h2 key={index}>{line.slice(3)}</h2> : line.startsWith('# ') ? <h1 key={index}>{line.slice(2)}</h1> : line.startsWith('- ') ? <li key={index}>{line.slice(2)}</li> : <p key={index}>{line || ' '}</p>)}</div>
  return <pre>{text}</pre>
}
function ContextPanel({ material, topics, activeTopic, onClose, onRefresh, onOpenTopic }: { material: Material; topics: Topic[]; activeTopic: TopicMap | null; onClose(): void; onRefresh(): Promise<void>; onOpenTopic(topic: Topic): void }): React.ReactElement {
  const [adding, setAdding] = useState(false); const [editing, setEditing] = useState(false); const [title, setTitle] = useState(material.title); const [text, setText] = useState(material.extractedText ?? ''); const [saved, setSaved] = useState(true)
  const editable = material.type === 'note' || material.type === 'document' || (material.type === 'file' && /\.(md|txt|csv|json|html?)$/i.test(material.sourcePath ?? material.storedPath ?? ''))
  useEffect(() => { setTitle(material.title); setText(material.extractedText ?? ''); setEditing(false); setSaved(true) }, [material.id])
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (editing && (event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 's') { event.preventDefault(); void save() } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) })
  const save = async () => { await window.materialMap.materials.saveText(material.id, title, text); setSaved(true); setEditing(false); await onRefresh() }
  const addToTopic = async (topicId: string) => { await window.materialMap.topics.addMaterial(topicId, material.id); setAdding(false); await onRefresh(); const topic = topics.find((item) => item.id === topicId); if (topic) onOpenTopic(topic) }
  return <aside className={`context-panel ${editing ? 'editing' : ''}`}><header><div className={`material-type ${material.type}`}>{materialIcon(material.type)}<span>{material.type}</span></div><button className="icon-button" onClick={onClose}><X size={18}/></button></header>
    {editing ? <><input className="editor-title" value={title} onChange={(event) => { setTitle(event.target.value); setSaved(false) }}/><div className="document-editor"><section><span>编辑</span><textarea className="material-editor" value={text} onChange={(event) => { setText(event.target.value); setSaved(false) }}/></section><section><span>预览</span><div className="document-preview"><MaterialPreview material={material} text={text}/></div></section></div><div className="editor-actions"><span>{saved ? '已保存' : '未保存'}</span><button className="secondary-button" onClick={() => setEditing(false)}>取消</button><button className="primary-button" disabled={saved} onClick={() => void save()}>保存</button></div></> : <><h2>{material.title}</h2><div className="panel-meta"><span><Clock3 size={14}/>{toDay(material.occurredAt)} · {material.occurredAtSource === 'content' ? '内容日期' : material.occurredAtSource === 'manual' ? '手动修正' : '导入日期'}</span></div><div className="preview"><p>{material.extractedText || material.excerpt || material.error || '材料仍在等待处理。'}</p></div><div className="panel-actions">{editable ? <button className="secondary-button" onClick={() => setEditing(true)}>编辑内容</button> : <button className="secondary-button" onClick={() => void window.materialMap.materials.open(material.id)}>用默认程序打开</button>}</div></>}
    {material.error && <button className="retry-button" onClick={async () => { await window.materialMap.materials.retry(material.id); await onRefresh() }}><LoaderCircle size={15}/>重新处理</button>}<section className="panel-section"><div className="panel-section-title"><h3>所在主题</h3><button onClick={() => setAdding(!adding)}><Plus size={15}/></button></div>{adding && <div className="topic-picker">{topics.length ? topics.map((topic) => <button key={topic.id} onClick={() => void addToTopic(topic.id)}>{topic.name}</button>) : <p>先在左侧创建一个主题。</p>}</div>}{activeTopic?.materials.some((item) => item.id === material.id) && <div className="relationship-list">{activeTopic.relations.filter((relation) => relation.sourceMaterialId === material.id || relation.targetMaterialId === material.id).map((relation) => <div className="relationship" key={relation.id}><Network size={14}/><div><span>{relation.label}</span>{relation.evidenceText && <p className="relationship-evidence">{relation.evidenceText}</p>}</div><button title="删除关联" onClick={async () => { await window.materialMap.relations.delete(relation.id); await onRefresh() }}><X size={13}/></button></div>)}</div>}</section><section className="panel-section"><h3>时间</h3><input className="date-input" type="date" defaultValue={material.occurredAt?.slice(0, 10)} onChange={async (event) => { if (event.target.value) { await window.materialMap.materials.date(material.id, `${event.target.value}T00:00:00.000Z`); await onRefresh() } }}/></section></aside> }
function TopicCanvas({ map, materials, onRefresh, onSelect, onContext }: { map: TopicMap; materials: Material[]; onRefresh(): Promise<void>; onSelect(material: Material): void; onContext(material: Material, x: number, y: number): void }): React.ReactElement {
  const [newStream, setNewStream] = useState('')
  const [source, setSource] = useState('')
  const [analysis, setAnalysis] = useState<AnalysisStatus>({ running: 0, complete: 0, failed: 0, latestError: null })
  const [analysisResult, setAnalysisResult] = useState<string | null>(null)
  const [analyzing, setAnalyzing] = useState(false)
  const [hoverLane, setHoverLane] = useState<number | null>(null)
  const [dragging, setDragging] = useState<string | null>(null)
  const [connecting, setConnecting] = useState<{ sourceId: string; x: number; y: number } | null>(null)
  const canvas = useRef<HTMLDivElement>(null)
  const refreshAnalysis = async () => setAnalysis(await window.materialMap.analysis.status(map.topic.id) as AnalysisStatus)
  useEffect(() => { void refreshAnalysis(); const timer = window.setInterval(() => void refreshAnalysis(), 1500); return () => window.clearInterval(timer) }, [map.topic.id])
  const dated = map.materials.map((material) => ({ material, time: new Date(material.occurredAt || material.importedAt).getTime() })).filter(({ time }) => Number.isFinite(time)).sort((a, b) => a.time - b.time)
  const min = dated[0]?.time ?? Date.now()
  const max = dated.at(-1)?.time ?? min + 1
  const laneFor = (material: TopicMap['materials'][number]) => Math.max(0, map.workstreams.findIndex((stream) => stream.id === workstreamOf(material)))
  const xFor = (material: TopicMap['materials'][number]) => { const time = new Date(material.occurredAt || material.importedAt).getTime(); return 14 + ((Number.isFinite(time) ? time : min) - min) / Math.max(max - min, 1) * 62 }
  const yFor = (lane: number) => 20 + lane * (61 / Math.max(map.workstreams.length, 1))
  const nodeY = (material: TopicMap['materials'][number]) => {
    const peers = map.materials.filter((item) => laneFor(item) === laneFor(material) && Math.abs(new Date(item.occurredAt || item.importedAt).getTime() - new Date(material.occurredAt || material.importedAt).getTime()) < 24 * 60 * 60 * 1000).sort((a, b) => a.id.localeCompare(b.id))
    const offset = (peers.findIndex((item) => item.id === material.id) - (peers.length - 1) / 2) * 4
    return yFor(laneFor(material)) + offset
  }
  const pointerLane = (clientY: number) => { const box = canvas.current?.getBoundingClientRect(); if (!box || !map.workstreams.length) return null; const percent = ((clientY - box.top) / box.height) * 100; const spacing = 61 / map.workstreams.length; return Math.max(0, Math.min(map.workstreams.length - 1, Math.round((percent - (yFor(0) + 6)) / spacing))) }
  const attach = async () => { const material = materials.find((item) => item.id === source); if (!material) return; await window.materialMap.topics.addMaterial(map.topic.id, material.id); setAnalysisResult('已加入主题，AI 正在分析…'); await onRefresh(); await refreshAnalysis() }
  const analyzeTopic = async () => { setAnalyzing(true); setAnalysisResult('正在分析主题材料…'); try { const result = await window.materialMap.analysis.topic(map.topic.id) as AnalysisSummary; const failures = result.failures.length ? `；${result.failures.length} 项失败：${result.failures[0].error}` : ''; setAnalysisResult(`已分析 ${result.processed} 份材料，新增 ${result.addedWorkstreams} 条工作线、${result.addedRelations} 条关系${failures}`); await onRefresh(); await refreshAnalysis() } catch (error) { setAnalysisResult(error instanceof Error ? error.message : '分析失败。') } finally { setAnalyzing(false) } }
  const createRelation = async (sourceId: string, targetId: string) => { if (sourceId === targetId) return; await window.materialMap.relations.create({ sourceMaterialId: sourceId, targetMaterialId: targetId, label: '关联', relationType: 'related', evidenceText: null, evidenceMaterialId: sourceId, confidence: null, createdBy: 'manual' }); await onRefresh() }
  const onCanvasMove = (event: React.PointerEvent<HTMLDivElement>) => { if (dragging) setHoverLane(pointerLane(event.clientY)); if (connecting) { const box = canvas.current?.getBoundingClientRect(); if (box) setConnecting((old) => old ? { ...old, x: ((event.clientX - box.left) / box.width) * 100, y: ((event.clientY - box.top) / box.height) * 100 } : null) } }
  const onCanvasUp = async (event: React.PointerEvent<HTMLDivElement>) => { if (dragging) { const material = map.materials.find((item) => item.id === dragging); const lane = pointerLane(event.clientY); if (material && lane !== null && map.workstreams[lane]) await window.materialMap.workstreams.moveMaterial(map.topic.id, material.id, map.workstreams[lane].id); setDragging(null); setHoverLane(null); await onRefresh() } if (connecting) { const target = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>('[data-material-id]')?.dataset.materialId; const origin = connecting.sourceId; setConnecting(null); if (target) await createRelation(origin, target) } }
  const cancelPointerAction = () => { setDragging(null); setHoverLane(null); setConnecting(null) }
  const connectionMaterial = connecting ? map.materials.find((item) => item.id === connecting.sourceId) : null
  return <section className="topic-view">
    <div className="topic-toolbar"><div><span className="view-pill"><Network size={14}/>二维关系图</span><p>时间锁定横轴。拖动材料到工作线以调整归属；从卡片右侧端口拖到另一材料即可建立关系。</p></div><div className="map-actions"><button className="secondary-button" disabled={analyzing || analysis.running > 0 || map.materials.length < 2} onClick={() => void analyzeTopic()}><Sparkles size={15}/>{analyzing || analysis.running > 0 ? '分析中…' : '分析主题'}</button><select value={source} onChange={(event) => setSource(event.target.value)}><option value="">选择未加入材料</option>{materials.filter((material) => !map.materials.some((item) => item.id === material.id)).map((material) => <option key={material.id} value={material.id}>{material.title}</option>)}</select><button className="secondary-button" onClick={() => void attach()}><Plus size={15}/>加入主题</button></div></div>
    {(analysisResult || analysis.running || analysis.latestError) && <div className={`analysis-status ${analysis.latestError ? 'failed' : analysis.running ? 'running' : ''}`}>{analysis.running ? `AI 正在分析 ${analysis.running} 份材料…` : analysisResult ?? analysis.latestError}</div>}
    <div ref={canvas} className="topic-canvas interactive" onPointerMove={onCanvasMove} onPointerUp={(event) => void onCanvasUp(event)} onPointerCancel={cancelPointerAction}>
      <div className="axis-title y">工作线</div><div className="axis-title x">时间</div><div className="axis-line horizontal"/><div className="axis-line vertical"/>
      {map.workstreams.map((stream, index) => <div className={`workstream ${hoverLane === index ? 'drop-target' : ''}`} key={stream.id} style={{ top: `${yFor(index) + 6}%` }}><div className="workstream-label"><span>{stream.name}</span><button title="重命名工作线" onClick={() => { const name = window.prompt('工作线名称', stream.name); if (name) void window.materialMap.workstreams.update(stream.id, name).then(onRefresh) }}><MoreHorizontal size={15}/></button></div><div className="lane-line"/></div>)}
      <svg className="map-edges" viewBox="0 0 100 100" preserveAspectRatio="none">
        {map.relations.map((relation) => { const start = map.materials.find((item) => item.id === relation.sourceMaterialId); const end = map.materials.find((item) => item.id === relation.targetMaterialId); if (!start || !end) return null; return <line key={relation.id} x1={xFor(start) + 7} y1={nodeY(start) + 6} x2={xFor(end) + 7} y2={nodeY(end) + 6} /> })}
        {connecting && connectionMaterial && <line className="connecting-edge" x1={xFor(connectionMaterial) + 7} y1={yFor(laneFor(connectionMaterial)) + 6} x2={connecting.x} y2={connecting.y}/>} 
      </svg>
      {map.workstreams.length === 0 && <div className="canvas-hint">添加一条工作线，为材料建立纵向语义。</div>}
      {map.materials.map((material) => { const lane = laneFor(material); return <button className={`map-node ${dragging === material.id ? 'dragging' : ''}`} data-material-id={material.id} key={material.id} style={{ left: `${xFor(material)}%`, top: `${nodeY(material)}%` }} onContextMenu={(event) => { event.preventDefault(); event.stopPropagation(); onContext(material, event.clientX, event.clientY) }} onPointerDown={(event) => { if ((event.target as HTMLElement).closest('.connection-port')) return; event.currentTarget.setPointerCapture(event.pointerId); setDragging(material.id); onSelect(material) }} onClick={() => onSelect(material)}><span className={`node-dot ${material.type}`}/><small>{toDay(material.occurredAt)}</small><strong>{material.title}</strong><span className="connection-port" title="拖动到另一材料以创建关系" onPointerDown={(event) => { event.stopPropagation(); const box = canvas.current?.getBoundingClientRect(); if (box) { (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); setConnecting({ sourceId: material.id, x: ((event.clientX - box.left) / box.width) * 100, y: ((event.clientY - box.top) / box.height) * 100 }) } }}/></button> })}
    </div>
    <div className="map-bottom"><form onSubmit={(event) => { event.preventDefault(); if (newStream.trim()) void window.materialMap.workstreams.create(map.topic.id, newStream.trim()).then(() => { setNewStream(''); return onRefresh() }) }}><input value={newStream} onChange={(event) => setNewStream(event.target.value)} placeholder="添加工作线，例如：研究、写作、交付"/><button className="secondary-button"><Plus size={15}/>添加工作线</button></form></div>
  </section>
}
function NoteDialog({ onClose, onSave }: { onClose(): void; onSave(title:string,text:string,format:'note'|'md'|'txt'|'csv'|'json'|'html'): void }): React.ReactElement { const [title,setTitle]=useState(''); const [text,setText]=useState(''); const [format,setFormat]=useState<'note'|'md'|'txt'|'csv'|'json'|'html'>('note'); return <Modal title="新建材料" onClose={onClose}><label>材料类型<select value={format} onChange={(e)=>setFormat(e.target.value as typeof format)}><option value="note">笔记</option><option value="md">Markdown 文档</option><option value="txt">纯文本文件</option><option value="csv">CSV 文件</option><option value="json">JSON 文件</option><option value="html">HTML 文件</option></select></label><input autoFocus value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="材料标题"/><textarea value={text} onChange={(e)=>setText(e.target.value)} placeholder="输入或粘贴内容…"/><button className="primary-button" disabled={!title.trim()} onClick={()=>onSave(title,text,format)}>创建并保存</button></Modal> }
function LinkDialog({ onClose, onSave }: { onClose(): void; onSave(url:string): void }): React.ReactElement { const [url,setUrl]=useState(''); return <Modal title="添加链接" onClose={onClose}><p className="dialog-note">应用只会访问一次页面，用于读取标题、站点名称和公开摘要；不会抓取正文或后台更新。</p><input autoFocus value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="https://example.com"/><button className="primary-button" disabled={!/^https?:\/\//.test(url)} onClick={()=>onSave(url)}>添加并解析</button></Modal> }
function TopicDialog({ onClose, onSave }: { onClose(): void; onSave(name:string,description:string): void }): React.ReactElement { const [name,setName]=useState(''); const [description,setDescription]=useState(''); return <Modal title="新建主题" onClose={onClose}><input autoFocus value={name} onChange={(e)=>setName(e.target.value)} placeholder="主题名称，例如：毕业论文"/><textarea value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="这个主题想梳理什么？"/><button className="primary-button" disabled={!name.trim()} onClick={()=>onSave(name,description)}>创建主题</button></Modal> }
function SettingsDialog({ onClose, topicId }: { onClose(): void; topicId?: string }): React.ReactElement {
  const [settings, setSettings] = useState<ModelSettings>({ profileId: null, provider: 'compatible', baseUrl: '', chatModel: '', embeddingModel: '', allowCloud: false, enabled: false })
  const [config, setConfig] = useState<ProviderProfile | null>(null)
  const [service, setService] = useState<'deepseek'|'relay'|'ollama'|'custom'>('deepseek')
  const [draft, setDraft] = useState({ provider: 'compatible' as ModelSettings['provider'], wireApi: 'chat_completions' as 'chat_completions'|'responses', baseUrl: '', apiKey: '' })
  const [result, setResult] = useState('')
  const load = async () => { const [nextSettings, active] = await Promise.all([window.materialMap.settings.get(), window.materialMap.aiConfig.get()]); setSettings(nextSettings); setConfig(active); if (active) { setDraft({ provider: active.provider, wireApi: active.wireApi, baseUrl: active.baseUrl, apiKey: '' }); setService(active.baseUrl.includes('deepseek') ? 'deepseek' : active.baseUrl.includes('code.heihuzi.ai') ? 'relay' : active.provider === 'ollama' ? 'ollama' : 'custom') } }
  useEffect(() => { void load() }, [])
  const update = <K extends keyof ModelSettings>(key: K, value: ModelSettings[K]) => setSettings((old) => ({ ...old, [key]: value }))
  const chooseService = (next: typeof service) => { setService(next); if (next === 'deepseek') { setDraft((old) => ({ ...old, provider: 'compatible', wireApi: 'chat_completions', baseUrl: 'https://api.deepseek.com' })); if (!settings.chatModel) update('chatModel', 'deepseek-chat') } else if (next === 'relay') setDraft((old) => ({ ...old, provider: 'compatible', wireApi: 'responses', baseUrl: 'https://code.heihuzi.ai' })); else if (next === 'ollama') setDraft((old) => ({ ...old, provider: 'ollama', wireApi: 'chat_completions', baseUrl: 'http://localhost:11434' })) }
  const save = async () => { try { const active = await window.materialMap.aiConfig.save({ ...draft, apiKey: draft.apiKey || undefined }) as ProviderProfile; const nextSettings = { ...settings, profileId: active.id, provider: active.provider, baseUrl: active.baseUrl }; await window.materialMap.settings.save(nextSettings); setSettings(nextSettings); setConfig(active); setDraft((old) => ({ ...old, apiKey: '' })); setResult(`已保存。整个应用现在使用 ${service === 'deepseek' ? 'DeepSeek' : service === 'relay' ? '中转站' : service === 'ollama' ? 'Ollama' : '当前自定义服务'}。`) } catch (error) { setResult(error instanceof Error ? error.message : '保存失败。') } }
  return <Modal title="模型与隐私" onClose={onClose}>
    <p className="dialog-note">选择一个服务商并保存后，搜索问答和主题分析都会使用这一套当前 AI 设置。API Key 只加密保存在本机，不会进入工作区或导出包。</p>
    <label>服务商<select value={service} onChange={(event) => chooseService(event.target.value as typeof service)}><option value="deepseek">DeepSeek</option><option value="relay">OpenAI 兼容中转站</option><option value="ollama">本机 Ollama</option><option value="custom">自定义服务</option></select></label>
    {service === 'custom' && <label>服务协议<select value={draft.provider} onChange={(event) => setDraft((old) => ({ ...old, provider: event.target.value as ModelSettings['provider'] }))}><option value="compatible">OpenAI 兼容</option><option value="ollama">本机 Ollama</option><option value="anthropic">Anthropic Claude</option><option value="gemini">Google Gemini</option></select></label>}
    {draft.provider === 'compatible' && <label>API 调用协议<select value={draft.wireApi} disabled={service === 'relay'} onChange={(event) => setDraft((old) => ({ ...old, wireApi: event.target.value as 'chat_completions'|'responses' }))}><option value="chat_completions">OpenAI Chat Completions</option><option value="responses">OpenAI Responses</option></select></label>}
    <label>服务地址<input value={draft.baseUrl} onChange={(event) => setDraft((old) => ({ ...old, baseUrl: event.target.value }))}/></label>
    {draft.provider !== 'ollama' && <label>API Key<input type="password" value={draft.apiKey} onChange={(event) => setDraft((old) => ({ ...old, apiKey: event.target.value }))} placeholder={config?.hasApiKey ? '已保存，留空则不更改' : '粘贴 API Key'}/></label>}
    <label>聊天模型<input value={settings.chatModel} onChange={(event) => update('chatModel', event.target.value)} placeholder={service === 'deepseek' ? 'deepseek-chat' : '填写模型名称'}/></label>
    <label>嵌入模型<input value={settings.embeddingModel} onChange={(event) => update('embeddingModel', event.target.value)} placeholder="可选"/></label>
    {draft.provider !== 'ollama' && <label className="checkbox"><input type="checkbox" checked={settings.allowCloud} onChange={(event) => update('allowCloud', event.target.checked)}/>我理解分析文本会发送到所选外部服务</label>}
    <label className="checkbox"><input type="checkbox" checked={settings.enabled} onChange={(event) => update('enabled', event.target.checked)}/>开启自动分析</label>
    <div className="dialog-actions"><button className="secondary-button" onClick={async () => { if (window.confirm('清理旧的 AI 配置及其本机 Key？')) { await window.materialMap.aiConfig.clearLegacy(); await load(); setResult('旧 AI 配置已清理。') } }}>清理旧配置</button><button className="secondary-button" onClick={async () => { const steps = await window.materialMap.settings.validate(settings, topicId); setResult(steps.map((step: { id:string; ok:boolean; detail:string; durationMs:number }) => `${step.ok ? '通过' : '失败'} ${step.id}：${step.detail} (${step.durationMs}ms)`).join('\n')) }}>验证当前 AI</button><button className="primary-button" disabled={!draft.baseUrl.trim() || !settings.chatModel.trim()} onClick={() => void save()}>保存并应用</button></div>{result && <p className="result-text">{result}</p>}
  </Modal>
}
function Modal({ title, onClose, children }: { title:string; onClose():void; children:React.ReactNode }): React.ReactElement { return <div className="modal-backdrop"><section className="modal"><header><h2>{title}</h2><button className="icon-button" onClick={onClose}><X size={18}/></button></header><div className="modal-body">{children}</div></section></div> }
