export type MaterialType = 'file' | 'note' | 'document' | 'link'
export interface Material { id:string; type:MaterialType; title:string; mimeType?:string|null; sourcePath?:string|null; storedPath?:string|null; url?:string|null; siteName?:string|null; excerpt?:string|null; extractedText?:string|null; importedAt:string; occurredAt?:string|null; occurredAtSource:string; status:string; error?:string|null; hash?:string|null; availability?:'available'|'unavailable'; lastIndexedAt?:string|null }
export interface FolderSource { id:string; rootPath:string; enabled:boolean; includePatterns:string[]; excludePatterns:string[]; watchEnabled:boolean; createdAt:string; updatedAt:string }
export interface SearchHit { materialId:string; chunkId:string|null; title:string; text:string; score:number; sourcePath:string|null; pageNumber:number|null; heading:string|null; availability:'available'|'unavailable' }
export interface GroundedCitation { id:string; materialId:string; chunkId:string|null; title:string; excerpt:string; sourcePath:string|null; pageNumber:number|null; heading:string|null }
export interface GroundedAnswer { answer:string; citations:GroundedCitation[]; confidence:'grounded'|'insufficient-evidence'; retrievalMode:'fts'|'hybrid'|'fallback'; model:string|null; retrievedChunks?:number; citationMode?:'model'|'inferred'|'catalog'; answerMode?:'model'|'local-fallback'; toolCalls?:Array<{name:string;arguments:Record<string,unknown>}>; answerScope?:'workspace'|'general'|'action' }
export interface KnowledgeChatTurn { role:'user'|'assistant'; content:string }
export interface KnowledgeQuestion { question:string; history?:KnowledgeChatTurn[] }
export interface MaterialTag { materialId:string; tag:string; source:'title'|'heading'|'phrase'; weight:number }
export type EntityType = 'file_reference'|'technology'|'project'
export interface Entity { id:string; text:string; normalized:string; type:EntityType; weight:number }
export interface RelationshipEvidence { id:string; relationId:string; type:'explicit_reference'|'entity_overlap'|'structural'; score:number; sourceMaterialId:string; targetMaterialId:string; sourceEntityId:string|null; targetEntityId:string|null; sourceOffset:number|null; targetOffset:number|null; sourceEndOffset?:number|null; targetEndOffset?:number|null; sourcePageNumber?:number|null; targetPageNumber?:number|null; sourceHeading?:string|null; targetHeading?:string|null; text:string; createdAt:string }
export type MaterialRelationStatus = 'visible'|'hidden'|'fixed'
export interface MaterialRelation { id:string; sourceMaterialId:string; targetMaterialId:string; score:number; relationType:'references'|'shares_entities'|'nearby'; status:MaterialRelationStatus; updatedAt:string; target:Material; evidence:RelationshipEvidence[] }
export interface RelationAiExplanation { supported:boolean; sourceMaterialId:string; targetMaterialId:string; relationType:string; label:string; explanation:string; confidence:number }
export interface TopicRelationCandidateRecord { id:string; topicId:string; sourceMaterialId:string; targetMaterialId:string; sharedTags:string[]; score:number; status:'visible'|'hidden'|'accepted'; createdAt:string; updatedAt:string }
export interface TopicProposal { id:string; topicId:string; kind:string; reason:string; evidence:string; materialId?:string|null; relationId?:string|null; payload:Record<string, unknown>; status:'pending'|'accepted'|'archived'; createdAt:string; updatedAt:string }
export interface Topic { id:string; name:string; description?:string|null; createdAt:string; archivedAt?:string|null; color?:string }
export interface Workstream { id:string; topicId:string; name:string; position:number; source:string }
export type ArrowStyle = 'none' | 'triangle' | 'open-triangle' | 'diamond'
export type RelationWaypoint = { x:number; y:number }
export type LineDash = 'auto'|'solid'|'dashed'|'dotted'
export interface Relation { id:string; sourceMaterialId:string; targetMaterialId:string; label:string; relationType:string; evidenceText?:string|null; evidenceMaterialId?:string|null; confidence?:number|null; createdBy:'system'|'ai'|'manual'|'local'; createdAt:string; lineColor?:string|null; sourceArrow?:boolean; sourceArrowStyle?:ArrowStyle|null; targetArrowStyle?:ArrowStyle; animated?:boolean; archived?:boolean; branchIndex?:number; lineKind?:'auto'|'straight'|'bezier'|'orthogonal'; sourceHandle?:string|null; targetHandle?:string|null; lineWidth?:number; lineDash?:LineDash; routePoints?:RelationWaypoint[]; labelAnchor?:number }
export interface TopicAnalysisRun { id:string; topicId:string; topicRevision:number; stage:'preparing'|'candidates'|'verifying'|'applying'|'complete'|'failed'|'cancelled'; completed:number; total:number; addedRelations:number; rejectedCandidates:number; error:string|null; summary:string|null; createdAt:string; updatedAt:string }
export interface TopicHistoryStatus { undo:boolean; redo:boolean; cursor:number }
export interface TopicMap { topic:Topic; materials:Array<Material & {workstreamId?:string|null;canvasX?:number|null;canvasY?:number|null;positionSource?:'auto'|'manual';cardColor?:string|null;cardTags?:string[];tags?:MaterialTag[];cardNote?:string|null;sequence?:number|null;sequenceSource?:string;addedAt?:string|null;displayTitle?:string|null;displayExcerpt?:string|null;cardWidth?:number|null;cardHeight?:number|null;cardTextColor?:string|null;cardFontSize?:number|null;cardCollapsed?:boolean;cardZIndex?:number}>; workstreams:Workstream[]; relations:Relation[]; candidates:TopicRelationCandidateRecord[]; history?:TopicHistoryStatus }
export interface AnalysisSummary { topicId:string; processed:number; addedWorkstreams:number; addedRelations:number; failures:Array<{materialId:string;error:string}> }
export interface AnalysisStatus { running:number; complete:number; failed:number; latestError:string|null }
export interface Workspace { id:string; name:string; root:string; encrypted:boolean }
export interface ModelSettings { profileId:string|null; provider:'ollama'|'compatible'|'anthropic'|'gemini'; baseUrl:string; chatModel:string; embeddingModel:string; allowCloud:boolean; enabled:boolean }
export interface ProviderProfile { id:string; name:string; provider:ModelSettings['provider']; baseUrl:string; wireApi:'chat_completions'|'responses'; models:string[]; recommendedModel:string|null; updatedAt:string; hasApiKey:boolean }
