import { contextBridge, ipcRenderer, webUtils } from 'electron'

const api = {
  chooseDirectory: () => ipcRenderer.invoke('dialog:chooseDirectory'), chooseFiles: () => ipcRenderer.invoke('dialog:chooseFiles'), choosePackage: () => ipcRenderer.invoke('dialog:choosePackage'), savePackage: () => ipcRenderer.invoke('dialog:savePackage'), filePath: (file: File) => webUtils.getPathForFile(file),
  workspace: { create: (root: string, name: string, password?: string) => ipcRenderer.invoke('workspace:create', root, name, password), open: (root: string, password?: string) => ipcRenderer.invoke('workspace:open', root, password), import: (file: string, destination: string) => ipcRenderer.invoke('workspace:import', file, destination), export: (destination: string) => ipcRenderer.invoke('workspace:export', destination), recent: () => ipcRenderer.invoke('workspace:recent'), forgetRecent: (root: string) => ipcRenderer.invoke('workspace:forgetRecent', root), onMenu: (channel: string, callback: () => void) => ipcRenderer.on(channel, callback) },
  materials: { list: () => ipcRenderer.invoke('materials:list'), listWithTopics: () => ipcRenderer.invoke('materials:listWithTopics'), import: (file: string, duplicate = false) => ipcRenderer.invoke('materials:import', file, duplicate), note: (title: string, text: string) => ipcRenderer.invoke('materials:note', title, text), document: (title: string, text: string, format: 'md'|'txt'|'csv'|'json'|'html') => ipcRenderer.invoke('materials:document', title, text, format), saveText: (id: string, title: string, text: string) => ipcRenderer.invoke('materials:saveText', id, title, text), open: (id: string) => ipcRenderer.invoke('materials:open', id), rename: (id: string, title: string) => ipcRenderer.invoke('materials:rename', id, title), delete: (id: string) => ipcRenderer.invoke('materials:delete', id), importNewVersion: (id: string) => ipcRenderer.invoke('materials:importNewVersion', id), link: (url: string) => ipcRenderer.invoke('materials:link', url), retry: (id: string) => ipcRenderer.invoke('materials:retry', id), date: (id: string, date: string) => ipcRenderer.invoke('materials:date', id, date) },
  topics: { list: () => ipcRenderer.invoke('topics:list'), listArchived: () => ipcRenderer.invoke('topics:listArchived'), create: (name: string, description = '') => ipcRenderer.invoke('topics:create', name, description), addMaterial: (topicId: string, materialId: string, workstreamId?: string) => ipcRenderer.invoke('topics:addMaterial', topicId, materialId, workstreamId), addMaterials: (topicId: string, materialIds: string[]) => ipcRenderer.invoke('topics:addMaterials', topicId, materialIds), forMaterial: (materialId: string) => ipcRenderer.invoke('topics:forMaterial', materialId), removeMaterial: (topicId: string, materialId: string) => ipcRenderer.invoke('topics:removeMaterial', topicId, materialId), archive: (topicId: string) => ipcRenderer.invoke('topics:archive', topicId), restore: (topicId: string) => ipcRenderer.invoke('topics:restore', topicId), deleteArchived: (topicId: string) => ipcRenderer.invoke('topics:deleteArchived', topicId), positionMaterial: (topicId: string, materialId: string, x: number, y: number) => ipcRenderer.invoke('topics:positionMaterial', topicId, materialId, x, y), layout: (topicId: string, positions: Array<{ materialId: string; x: number; y: number }>) => ipcRenderer.invoke('topics:layout', topicId, positions), updateCardStyle: (topicId: string, materialId: string, input: { color?: string | null; tags?: string[]; note?: string | null }) => ipcRenderer.invoke('topics:updateCardStyle', topicId, materialId, input), updateRelationStyle: (topicId: string, relationId: string, input: { color?: string | null; sourceArrow?: boolean; sourceArrowStyle?: 'none'|'triangle'|'open-triangle'|'diamond'; targetArrowStyle?: 'none'|'triangle'|'open-triangle'|'diamond'; animated?: boolean; archived?: boolean; lineKind?: 'auto' | 'straight' | 'bezier' | 'orthogonal' }) => ipcRenderer.invoke('topics:updateRelationStyle', topicId, relationId, input), map: (topicId: string) => ipcRenderer.invoke('topics:map', topicId) },
  workstreams: { create: (topicId: string, name: string) => ipcRenderer.invoke('workstreams:create', topicId, name), update: (id: string, name: string) => ipcRenderer.invoke('workstreams:update', id, name), delete: (id: string) => ipcRenderer.invoke('workstreams:delete', id), moveMaterial: (topicId: string, materialId: string, workstreamId: string | null) => ipcRenderer.invoke('workstreams:moveMaterial', topicId, materialId, workstreamId) },
  cardOrder: { update: (topicId: string, materialId: string, sequence: number) => ipcRenderer.invoke('topics:updateCardOrder', topicId, materialId, sequence), reset: (topicId: string) => ipcRenderer.invoke('topics:resetCardOrder', topicId) },
  relations: { create: (relation: unknown) => ipcRenderer.invoke('relations:create', relation), update: (id: string, label: string) => ipcRenderer.invoke('relations:update', id, label), delete: (id: string) => ipcRenderer.invoke('relations:delete', id) },
  analysis: { topic: (topicId: string) => ipcRenderer.invoke('analysis:topic', topicId), status: (topicId: string) => ipcRenderer.invoke('analysis:status', topicId) },
  demo: { create: () => ipcRenderer.invoke('demo:create') },
  clipboard: { readText: () => ipcRenderer.invoke('clipboard:readText') }, search: (query: string) => ipcRenderer.invoke('search', query), jobs: () => ipcRenderer.invoke('jobs:list'), settings: { get: () => ipcRenderer.invoke('settings:get'), save: (settings: unknown) => ipcRenderer.invoke('settings:save', settings), test: (settings: unknown) => ipcRenderer.invoke('settings:test', settings), validate: (settings: unknown, topicId?: string) => ipcRenderer.invoke('settings:validate', settings, topicId) }, aiConfig: { get: () => ipcRenderer.invoke('ai-config:get'), save: (input: unknown) => ipcRenderer.invoke('ai-config:save', input), clearLegacy: () => ipcRenderer.invoke('ai-config:clearLegacy') }, profiles: { list: () => ipcRenderer.invoke('profiles:list'), presets: () => ipcRenderer.invoke('profiles:presets'), save: (input: unknown) => ipcRenderer.invoke('profiles:save', input), delete: (id: string) => ipcRenderer.invoke('profiles:delete', id), refreshModels: (id: string) => ipcRenderer.invoke('profiles:refreshModels', id) }, analyze: (topicId: string, materialId: string) => ipcRenderer.invoke('ai:analyze', topicId, materialId), ask: (question: string) => ipcRenderer.invoke('ai:ask', question), planTopicOperation: (topicId: string, question: string) => ipcRenderer.invoke('ai:planTopicOperation', topicId, question)
}
contextBridge.exposeInMainWorld('materialMap', api)
