import type { CanvasAiPlan, CanvasAiRequest, FolderSource, GroundedAnswer, KnowledgeQuestion, MaterialRelation, ModelSettings, ProviderProfile, ProviderProfileInput, Relation, RelationAiExplanation, RelationshipEvidence, SearchHit, TopicEditorCommand, TopicHistoryStatus, TopicProposal } from '../main/types'
declare global { interface Window { materialMap: {
  chooseDirectory(): Promise<string | null>; chooseFiles(): Promise<string[]>; choosePackage(): Promise<string | null>; savePackage(): Promise<string | null>; filePath(file: File): string
  workspace: { create(root: string, name: string, password?: string): Promise<unknown>; inspect(root: string): Promise<{ name:string; encrypted:boolean }>; inspectPackage(file: string): Promise<{ name:string; encrypted:boolean }>; open(root: string, password?: string): Promise<unknown>; import(file: string, destination: string, password?: string): Promise<unknown>; export(destination: string): Promise<void>; recent(): Promise<Array<{ root: string; name: string; openedAt: string }>>; forgetRecent(root: string): Promise<void>; onMenu(channel: string, callback: () => void): void }
  materials: { list(): Promise<unknown[]>; listWithTopics(): Promise<unknown[]>; import(file: string, duplicate?: boolean): Promise<unknown>; note(title: string, text: string): Promise<unknown>; document(title: string, text: string, format: 'md'|'txt'|'csv'|'json'|'html'): Promise<unknown>; saveText(id: string, title: string, text: string): Promise<unknown>; open(id: string): Promise<string>; rename(id: string, title: string): Promise<unknown>; delete(id: string): Promise<void>; importNewVersion(id: string): Promise<unknown>; link(url: string): Promise<unknown>; retry(id: string): Promise<void>; date(id: string, date: string): Promise<void>; relations(materialId: string, limit?: number, includeHidden?: boolean): Promise<MaterialRelation[]>; relationEvidence(relationId: string): Promise<RelationshipEvidence[]>; relationStatus(relationId: string, status: 'visible'|'hidden'|'fixed'): Promise<void>; fixRelation(relationId: string, topicId?: string): Promise<Relation> }
  sources: { list(): Promise<FolderSource[]>; add(input: Omit<FolderSource, 'id'|'createdAt'|'updatedAt'>): Promise<FolderSource>; update(id: string, input: Partial<Omit<FolderSource, 'id'|'createdAt'|'updatedAt'>>): Promise<FolderSource>; remove(id: string): Promise<void>; rescan(id: string): Promise<{ scanned:number; indexed:number; unavailable:number }>; pause(id: string): Promise<FolderSource>; capability(): Promise<{ fts:boolean; vector:{ available:boolean; version:string|null; error:string|null } }> }
  topics: { list(): Promise<unknown[]>; listArchived(): Promise<unknown[]>; create(name: string, description?: string): Promise<unknown>; addMaterial(topicId: string, materialId: string, workstreamId?: string): Promise<void>; addMaterials(topicId: string, materialIds: string[]): Promise<void>; forMaterial(materialId: string): Promise<unknown[]>; removeMaterial(topicId: string, materialId: string): Promise<void>; archive(topicId: string): Promise<void>; restore(topicId: string): Promise<unknown>; deleteArchived(topicId: string): Promise<void>; positionMaterial(topicId: string, materialId: string, x: number, y: number): Promise<void>; layout(topicId: string, positions: Array<{ materialId: string; x: number; y: number }>): Promise<void>; rebuildTopology(topicId: string): Promise<void>; updateView(topicId: string, input: { viewMode?: 'map'|'flow'; confirmedOnly?: boolean }): Promise<unknown>; updateCardStyle(topicId: string, materialId: string, input: { color?: string | null; tags?: string[]; note?: string | null }): Promise<void>; updateRelationStyle(topicId: string, relationId: string, input: { color?: string | null; sourceArrow?: boolean; sourceArrowStyle?: 'none'|'triangle'|'open-triangle'|'diamond'; targetArrowStyle?: 'none'|'triangle'|'open-triangle'|'diamond'; animated?: boolean; archived?: boolean; lineKind?: 'auto'|'straight'|'bezier'|'orthogonal'; sourceHandle?: string | null; targetHandle?: string | null; lineWidth?: number; lineDash?: 'auto'|'solid'|'dashed'|'dotted'; routePoints?: Array<{x:number;y:number}>; labelAnchor?: number }): Promise<void>; executeCommand(topicId: string, command: TopicEditorCommand): Promise<void>; undo(topicId: string): Promise<TopicHistoryStatus>; redo(topicId: string): Promise<TopicHistoryStatus>; history(topicId: string): Promise<TopicHistoryStatus>; proposals(topicId: string): Promise<TopicProposal[]>; acceptProposal(topicId: string, proposalId: string): Promise<TopicProposal>; acceptProposals(topicId: string, proposalIds: string[]): Promise<TopicProposal[]>; archiveProposal(topicId: string, proposalId: string): Promise<TopicProposal>; map(topicId: string): Promise<unknown> }
  workstreams: { create(topicId: string, name: string): Promise<unknown>; update(id: string, name: string): Promise<void>; delete(id: string): Promise<void>; moveMaterial(topicId: string, materialId: string, workstreamId: string | null): Promise<void> }
  cardOrder: { update(topicId: string, materialId: string, sequence: number): Promise<void>; reset(topicId: string): Promise<void> }
  relations: { create(relation: Omit<Relation, 'id' | 'createdAt'>): Promise<unknown>; update(id: string, label: string): Promise<void>; delete(id: string): Promise<void> }
  clipboard: { readText(): Promise<string> }; search(query: string): Promise<SearchHit[]>; jobs(): Promise<unknown[]>; settings: { get(): Promise<ModelSettings>; save(settings: ModelSettings): Promise<void>; test(settings: ModelSettings): Promise<{ ok: boolean; message: string }>; validate(settings: ModelSettings, topicId?: string): Promise<Array<{ id:string; ok:boolean; detail:string; status?:number; durationMs:number }>> }; aiConfig: { get(): Promise<ProviderProfile | null>; save(input: Omit<ProviderProfileInput, 'id'|'name'>): Promise<ProviderProfile>; clearLegacy(): Promise<void> }; profiles: { list(): Promise<ProviderProfile[]>; presets(): Promise<Array<{ name: string; provider: ProviderProfile['provider']; baseUrl: string; wireApi?: ProviderProfile['wireApi'] }>>; save(input: ProviderProfileInput): Promise<ProviderProfile>; delete(id: string): Promise<void>; refreshModels(id: string): Promise<ProviderProfile> }; ask(question: string | KnowledgeQuestion): Promise<GroundedAnswer>; planCanvas(input: CanvasAiRequest): Promise<CanvasAiPlan>; aiTools: { list(): Promise<ReadonlyArray<{ name: string; description: string; inputSchema: Record<string, unknown> }>>; call(name: string, args?: Record<string, unknown>): Promise<unknown> }; explainRelation(relationId: string): Promise<RelationAiExplanation>
} } }
export {}
