import type { ModelSettings, ProviderProfile, ProviderProfileInput, Relation } from '../main/types'
declare global { interface Window { materialMap: {
  chooseDirectory(): Promise<string | null>; chooseFiles(): Promise<string[]>; savePackage(): Promise<string | null>
  workspace: { create(root: string, name: string, password?: string): Promise<unknown>; open(root: string, password?: string): Promise<unknown>; export(destination: string): Promise<void>; recent(): Promise<Array<{ root: string; name: string; openedAt: string }>>; forgetRecent(root: string): Promise<void>; onMenu(channel: string, callback: () => void): void }
  materials: { list(): Promise<unknown[]>; import(file: string, duplicate?: boolean): Promise<unknown>; note(title: string, text: string): Promise<unknown>; document(title: string, text: string, format: 'md'|'txt'|'csv'|'json'|'html'): Promise<unknown>; saveText(id: string, title: string, text: string): Promise<unknown>; open(id: string): Promise<string>; rename(id: string, title: string): Promise<unknown>; delete(id: string): Promise<void>; importNewVersion(id: string): Promise<unknown>; link(url: string): Promise<unknown>; retry(id: string): Promise<void>; date(id: string, date: string): Promise<void> }
  topics: { list(): Promise<unknown[]>; create(name: string, description?: string): Promise<unknown>; addMaterial(topicId: string, materialId: string, workstreamId?: string): Promise<void>; map(topicId: string): Promise<unknown> }
  workstreams: { create(topicId: string, name: string): Promise<unknown>; update(id: string, name: string): Promise<void>; moveMaterial(topicId: string, materialId: string, workstreamId: string | null): Promise<void> }
  relations: { create(relation: Omit<Relation, 'id' | 'createdAt'>): Promise<unknown>; update(id: string, label: string): Promise<void>; delete(id: string): Promise<void> }
  search(query: string): Promise<unknown[]>; jobs(): Promise<unknown[]>; settings: { get(): Promise<ModelSettings>; save(settings: ModelSettings): Promise<void>; test(settings: ModelSettings): Promise<{ ok: boolean; message: string }>; validate(settings: ModelSettings, topicId?: string): Promise<Array<{ id:string; ok:boolean; detail:string; status?:number; durationMs:number }>> }; aiConfig: { get(): Promise<ProviderProfile | null>; save(input: Omit<ProviderProfileInput, 'id'|'name'>): Promise<ProviderProfile>; clearLegacy(): Promise<void> }; profiles: { list(): Promise<ProviderProfile[]>; presets(): Promise<Array<{ name: string; provider: ProviderProfile['provider']; baseUrl: string; wireApi?: ProviderProfile['wireApi'] }>>; save(input: ProviderProfileInput): Promise<ProviderProfile>; delete(id: string): Promise<void>; refreshModels(id: string): Promise<ProviderProfile> }; analyze(topicId: string, materialId: string): Promise<void>; ask(question: string): Promise<{ answer: string; citations: Array<{ id:string; title:string }> }>
} } }
export {}
