import { contextBridge, ipcRenderer, webUtils } from 'electron'
import type { KnowledgeQuestion } from '../main/types'

const api = {
  chooseDirectory: () => ipcRenderer.invoke('dialog:chooseDirectory'), chooseFiles: () => ipcRenderer.invoke('dialog:chooseFiles'), choosePackage: () => ipcRenderer.invoke('dialog:choosePackage'), savePackage: () => ipcRenderer.invoke('dialog:savePackage'), filePath: (file: File) => webUtils.getPathForFile(file),
  workspace: { create: (root: string, name: string, password?: string) => ipcRenderer.invoke('workspace:create', root, name, password), inspect: (root: string) => ipcRenderer.invoke('workspace:inspect', root), inspectPackage: (file: string) => ipcRenderer.invoke('workspace:inspectPackage', file), open: (root: string, password?: string) => ipcRenderer.invoke('workspace:open', root, password), import: (file: string, destination: string, password?: string) => ipcRenderer.invoke('workspace:import', file, destination, password), export: (destination: string) => ipcRenderer.invoke('workspace:export', destination), recent: () => ipcRenderer.invoke('workspace:recent'), forgetRecent: (root: string) => ipcRenderer.invoke('workspace:forgetRecent', root), onMenu: (channel: string, callback: () => void) => ipcRenderer.on(channel, callback) },
  materials: { list: () => ipcRenderer.invoke('materials:list'), listWithTopics: () => ipcRenderer.invoke('materials:listWithTopics'), import: (file: string, duplicate = false) => ipcRenderer.invoke('materials:import', file, duplicate), note: (title: string, text: string) => ipcRenderer.invoke('materials:note', title, text), document: (title: string, text: string, format: 'md'|'txt'|'csv'|'json'|'html') => ipcRenderer.invoke('materials:document', title, text, format), saveText: (id: string, title: string, text: string) => ipcRenderer.invoke('materials:saveText', id, title, text), open: (id: string) => ipcRenderer.invoke('materials:open', id), rename: (id: string, title: string) => ipcRenderer.invoke('materials:rename', id, title), delete: (id: string) => ipcRenderer.invoke('materials:delete', id), importNewVersion: (id: string) => ipcRenderer.invoke('materials:importNewVersion', id), link: (url: string) => ipcRenderer.invoke('materials:link', url), retry: (id: string) => ipcRenderer.invoke('materials:retry', id), date: (id: string, date: string) => ipcRenderer.invoke('materials:date', id, date), relations: (materialId: string, limit?: number, includeHidden?: boolean) => ipcRenderer.invoke('materials:relations', materialId, limit, includeHidden), relationEvidence: (relationId: string) => ipcRenderer.invoke('materials:relationEvidence', relationId), relationStatus: (relationId: string, status: 'visible'|'hidden'|'fixed') => ipcRenderer.invoke('materials:relationStatus', relationId, status), fixRelation: (relationId: string, topicId?: string) => ipcRenderer.invoke('materials:fixRelation', relationId, topicId) },
  sources: { list: () => ipcRenderer.invoke('sources:list'), add: (input: unknown) => ipcRenderer.invoke('sources:add', input), update: (id: string, input: unknown) => ipcRenderer.invoke('sources:update', id, input), remove: (id: string) => ipcRenderer.invoke('sources:remove', id), rescan: (id: string) => ipcRenderer.invoke('sources:rescan', id), pause: (id: string) => ipcRenderer.invoke('sources:pause', id), capability: () => ipcRenderer.invoke('sources:capability') },
  topics: { list: () => ipcRenderer.invoke('topics:list'), listArchived: () => ipcRenderer.invoke('topics:listArchived'), create: (name: string, description = '') => ipcRenderer.invoke('topics:create', name, description), addMaterial: (topicId: string, materialId: string, workstreamId?: string) => ipcRenderer.invoke('topics:addMaterial', topicId, materialId, workstreamId), addMaterials: (topicId: string, materialIds: string[]) => ipcRenderer.invoke('topics:addMaterials', topicId, materialIds), forMaterial: (materialId: string) => ipcRenderer.invoke('topics:forMaterial', materialId), removeMaterial: (topicId: string, materialId: string) => ipcRenderer.invoke('topics:removeMaterial', topicId, materialId), archive: (topicId: string) => ipcRenderer.invoke('topics:archive', topicId), restore: (topicId: string) => ipcRenderer.invoke('topics:restore', topicId), deleteArchived: (topicId: string) => ipcRenderer.invoke('topics:deleteArchived', topicId), positionMaterial: (topicId: string, materialId: string, x: number, y: number) => ipcRenderer.invoke('topics:positionMaterial', topicId, materialId, x, y), layout: (topicId: string, positions: Array<{ materialId: string; x: number; y: number }>) => ipcRenderer.invoke('topics:layout', topicId, positions), rebuildTopology: (topicId: string) => ipcRenderer.invoke('topics:rebuildTopology', topicId), updateCardStyle: (topicId: string, materialId: string, input: { color?: string | null; tags?: string[]; note?: string | null }) => ipcRenderer.invoke('topics:updateCardStyle', topicId, materialId, input), updateRelationStyle: (topicId: string, relationId: string, input: unknown) => ipcRenderer.invoke('topics:updateRelationStyle', topicId, relationId, input), executeCommand: (topicId: string, command: unknown) => ipcRenderer.invoke('topics:executeCommand', topicId, command), undo: (topicId: string) => ipcRenderer.invoke('topics:undo', topicId), redo: (topicId: string) => ipcRenderer.invoke('topics:redo', topicId), history: (topicId: string) => ipcRenderer.invoke('topics:history', topicId), map: (topicId: string) => ipcRenderer.invoke('topics:map', topicId) },
  workstreams: { create: (topicId: string, name: string) => ipcRenderer.invoke('workstreams:create', topicId, name), update: (id: string, name: string) => ipcRenderer.invoke('workstreams:update', id, name), delete: (id: string) => ipcRenderer.invoke('workstreams:delete', id), moveMaterial: (topicId: string, materialId: string, workstreamId: string | null) => ipcRenderer.invoke('workstreams:moveMaterial', topicId, materialId, workstreamId) },
  cardOrder: { update: (topicId: string, materialId: string, sequence: number) => ipcRenderer.invoke('topics:updateCardOrder', topicId, materialId, sequence), reset: (topicId: string) => ipcRenderer.invoke('topics:resetCardOrder', topicId) },
  relations: { create: (relation: unknown) => ipcRenderer.invoke('relations:create', relation), update: (id: string, label: string) => ipcRenderer.invoke('relations:update', id, label), delete: (id: string) => ipcRenderer.invoke('relations:delete', id) },
  demo: { create: () => ipcRenderer.invoke('demo:create') },
  clipboard: { readText: () => ipcRenderer.invoke('clipboard:readText') }, search: (query: string) => ipcRenderer.invoke('search', query), jobs: () => ipcRenderer.invoke('jobs:list'), settings: { get: () => ipcRenderer.invoke('settings:get'), save: (settings: unknown) => ipcRenderer.invoke('settings:save', settings), test: (settings: unknown) => ipcRenderer.invoke('settings:test', settings), validate: (settings: unknown, topicId?: string) => ipcRenderer.invoke('settings:validate', settings, topicId) }, aiConfig: { get: () => ipcRenderer.invoke('ai-config:get'), save: (input: unknown) => ipcRenderer.invoke('ai-config:save', input), clearLegacy: () => ipcRenderer.invoke('ai-config:clearLegacy') }, profiles: { list: () => ipcRenderer.invoke('profiles:list'), presets: () => ipcRenderer.invoke('profiles:presets'), save: (input: unknown) => ipcRenderer.invoke('profiles:save', input), delete: (id: string) => ipcRenderer.invoke('profiles:delete', id), refreshModels: (id: string) => ipcRenderer.invoke('profiles:refreshModels', id) }, ask: (question: string | KnowledgeQuestion) => ipcRenderer.invoke('ai:ask', question), explainRelation: async (relationId: string) => { const result = await ipcRenderer.invoke('ai:explainRelation', relationId); if (result && typeof result === 'object' && result.ok === false) throw new Error(String(result.message ?? 'AI 解释暂时不可用。')); if (result && typeof result === 'object' && 'ok' in result) { const { ok: _ok, ...explanation } = result; return explanation } return result }
}
contextBridge.exposeInMainWorld('materialMap', api)
