import { contextBridge, ipcRenderer } from 'electron'

const api = {
  chooseDirectory: () => ipcRenderer.invoke('dialog:chooseDirectory'), chooseFiles: () => ipcRenderer.invoke('dialog:chooseFiles'), savePackage: () => ipcRenderer.invoke('dialog:savePackage'),
  workspace: { create: (root: string, name: string, password?: string) => ipcRenderer.invoke('workspace:create', root, name, password), open: (root: string, password?: string) => ipcRenderer.invoke('workspace:open', root, password), export: (destination: string) => ipcRenderer.invoke('workspace:export', destination), recent: () => ipcRenderer.invoke('workspace:recent'), forgetRecent: (root: string) => ipcRenderer.invoke('workspace:forgetRecent', root), onMenu: (channel: string, callback: () => void) => ipcRenderer.on(channel, callback) },
  materials: { list: () => ipcRenderer.invoke('materials:list'), import: (file: string, duplicate = false) => ipcRenderer.invoke('materials:import', file, duplicate), note: (title: string, text: string) => ipcRenderer.invoke('materials:note', title, text), document: (title: string, text: string, format: 'md'|'txt'|'csv'|'json'|'html') => ipcRenderer.invoke('materials:document', title, text, format), saveText: (id: string, title: string, text: string) => ipcRenderer.invoke('materials:saveText', id, title, text), open: (id: string) => ipcRenderer.invoke('materials:open', id), rename: (id: string, title: string) => ipcRenderer.invoke('materials:rename', id, title), delete: (id: string) => ipcRenderer.invoke('materials:delete', id), importNewVersion: (id: string) => ipcRenderer.invoke('materials:importNewVersion', id), link: (url: string) => ipcRenderer.invoke('materials:link', url), retry: (id: string) => ipcRenderer.invoke('materials:retry', id), date: (id: string, date: string) => ipcRenderer.invoke('materials:date', id, date) },
  topics: { list: () => ipcRenderer.invoke('topics:list'), create: (name: string, description = '') => ipcRenderer.invoke('topics:create', name, description), addMaterial: (topicId: string, materialId: string, workstreamId?: string) => ipcRenderer.invoke('topics:addMaterial', topicId, materialId, workstreamId), map: (topicId: string) => ipcRenderer.invoke('topics:map', topicId) },
  workstreams: { create: (topicId: string, name: string) => ipcRenderer.invoke('workstreams:create', topicId, name), update: (id: string, name: string) => ipcRenderer.invoke('workstreams:update', id, name), moveMaterial: (topicId: string, materialId: string, workstreamId: string | null) => ipcRenderer.invoke('workstreams:moveMaterial', topicId, materialId, workstreamId) },
  relations: { create: (relation: unknown) => ipcRenderer.invoke('relations:create', relation), update: (id: string, label: string) => ipcRenderer.invoke('relations:update', id, label), delete: (id: string) => ipcRenderer.invoke('relations:delete', id) },
  analysis: { topic: (topicId: string) => ipcRenderer.invoke('analysis:topic', topicId), status: (topicId: string) => ipcRenderer.invoke('analysis:status', topicId) },
  demo: { create: () => ipcRenderer.invoke('demo:create') },
  search: (query: string) => ipcRenderer.invoke('search', query), jobs: () => ipcRenderer.invoke('jobs:list'), settings: { get: () => ipcRenderer.invoke('settings:get'), save: (settings: unknown) => ipcRenderer.invoke('settings:save', settings), test: (settings: unknown) => ipcRenderer.invoke('settings:test', settings), validate: (settings: unknown, topicId?: string) => ipcRenderer.invoke('settings:validate', settings, topicId) }, aiConfig: { get: () => ipcRenderer.invoke('ai-config:get'), save: (input: unknown) => ipcRenderer.invoke('ai-config:save', input), clearLegacy: () => ipcRenderer.invoke('ai-config:clearLegacy') }, profiles: { list: () => ipcRenderer.invoke('profiles:list'), presets: () => ipcRenderer.invoke('profiles:presets'), save: (input: unknown) => ipcRenderer.invoke('profiles:save', input), delete: (id: string) => ipcRenderer.invoke('profiles:delete', id), refreshModels: (id: string) => ipcRenderer.invoke('profiles:refreshModels', id) }, analyze: (topicId: string, materialId: string) => ipcRenderer.invoke('ai:analyze', topicId, materialId), ask: (question: string) => ipcRenderer.invoke('ai:ask', question)
}
contextBridge.exposeInMainWorld('materialMap', api)
