import { CheckCircle2, CircleAlert, Clock3, FilePlus2, FileText, Link2, LoaderCircle, Sparkles, Upload } from 'lucide-react'
import { useEffect, useState, type MouseEvent } from 'react'
import type { Material, Topic } from '../../types'

type Props = { materials: Material[]; materialTopics: Record<string, Topic[]>; topics: Topic[]; onSelect(material: Material): void; onContext(material: Material, x: number, y: number): void; onImport(): void; onLink(): void; onDemo(): void; onCreateTopic(materialIds: string[]): void }
const icon = (type: string) => type === 'link' ? <Link2 size={16} /> : type === 'note' ? <FilePlus2 size={16} /> : <FileText size={16} />
function status(material: Material): React.ReactElement { if (material.availability === 'unavailable') return <span className="status failed"><CircleAlert size={13} />原文件失联</span>; if (material.status === 'complete') return <span className="status complete"><CheckCircle2 size={13} />已整理</span>; if (material.status === 'failed') return <span className="status failed"><CircleAlert size={13} />需重试</span>; return <span className="status pending"><LoaderCircle size={13} />处理中</span> }
export function Workbench({ materials, materialTopics, topics, onSelect, onContext, onImport, onLink, onDemo, onCreateTopic }: Props): React.ReactElement {
  const [page, setPage] = useState(1); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [topicFilter, setTopicFilter] = useState(''); const [sort, setSort] = useState<'recent' | 'topic'>('recent'); const pageSize = 15
  const filtered = materials.filter((material) => !topicFilter || materialTopics[material.id]?.some((topic) => topic.id === topicFilter))
  const ordered = [...filtered].sort((a, b) => sort === 'recent' ? b.importedAt.localeCompare(a.importedAt) : (materialTopics[a.id]?.[0]?.name ?? '永未归类').localeCompare(materialTopics[b.id]?.[0]?.name ?? '永未归类', 'zh-CN'))
  const pageCount = Math.max(1, Math.ceil(ordered.length / pageSize)); const currentPage = Math.min(page, pageCount); const visible = ordered.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  useEffect(() => setPage(1), [topicFilter, sort, materials.length])
  const toggle = (material: Material, event: MouseEvent): void => { if (event.metaKey || event.ctrlKey || selectedIds.length) setSelectedIds((ids) => ids.includes(material.id) ? ids.filter((id) => id !== material.id) : [...ids, material.id]); else onSelect(material) }
  if (!materials.length) return <section className="workbench"><div className="empty-state"><div className="empty-icon"><Upload size={25} /></div><h2>从一份材料开始</h2><p>拖入文件、写一段笔记，或者添加链接。</p><div><button className="primary-button" onClick={onImport}><Upload size={17} />导入文件</button><button className="secondary-button" onClick={onLink}><Link2 size={17} />添加链接</button><button className="secondary-button" onClick={onDemo}><Sparkles size={17} />创建 AI 演示</button></div></div></section>
  return <section className="workbench"><div className="section-heading"><div><h2>最近导入</h2><p>材料完成分析后会自动补充摘要与关联。</p></div><div className="workbench-actions"><button className="secondary-button" onClick={onDemo}><Sparkles size={15} />创建 AI 演示</button><span>{filtered.length} 份材料</span></div></div><div className="workbench-filters"><select value={topicFilter} onChange={(event) => setTopicFilter(event.target.value)}><option value="">全部主题</option>{topics.map((topic) => <option key={topic.id} value={topic.id}>{topic.name}</option>)}</select><select value={sort} onChange={(event) => setSort(event.target.value as 'recent' | 'topic')}><option value="recent">最近导入</option><option value="topic">按主题</option></select></div>{selectedIds.length > 0 && <div className="bulk-material-actions"><span>已选择 {selectedIds.length} 份材料</span><button className="primary-button" onClick={() => onCreateTopic(selectedIds)}>从所选创建主题</button><button className="secondary-button" onClick={() => setSelectedIds([])}>取消选择</button></div>}<div className="material-grid">{visible.map((material) => <button key={material.id} className={`material-card ${selectedIds.includes(material.id) ? 'selected' : ''}`} onClick={(event) => toggle(material, event)} onContextMenu={(event) => { event.preventDefault(); onContext(material, event.clientX, event.clientY) }}><div className={`material-type ${material.type}`}>{icon(material.type)}<span>{material.type}</span></div><h3>{material.title}</h3><p>{material.availability === 'unavailable' ? '原始文件已失联，仍可查看最近快照。' : material.excerpt || material.error || '等待分析材料内容'}</p>{materialTopics[material.id]?.length > 0 && <div className="material-topic-tags">{materialTopics[material.id].slice(0, 3).map((topic) => <span key={topic.id} style={{ borderColor: topic.color, color: topic.color }}>{topic.name}</span>)}</div>}<div className="card-footer"><span><Clock3 size={13} />{material.importedAt.slice(0, 10)}</span>{status(material)}</div></button>)}</div>{pageCount > 1 && <div className="workbench-pagination"><button className="secondary-button" disabled={currentPage === 1} onClick={() => setPage((value) => value - 1)}>上一页</button><span>第 {currentPage} / {pageCount} 页</span><button className="secondary-button" disabled={currentPage === pageCount} onClick={() => setPage((value) => value + 1)}>下一页</button></div>}</section>
}
